<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260314042519 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE greeting_id_seq CASCADE');
        $this->addSql('CREATE TABLE caterer_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, business_name VARCHAR(255) NOT NULL, tagline VARCHAR(255) DEFAULT NULL, description TEXT NOT NULL, cuisine_types JSON NOT NULL, service_styles JSON NOT NULL, service_area VARCHAR(255) NOT NULL, price_range VARCHAR(10) NOT NULL, cover_image_url VARCHAR(500) DEFAULT NULL, gallery_images JSON NOT NULL, average_rating NUMERIC(3, 2) DEFAULT NULL, review_count INT NOT NULL, is_verified BOOLEAN NOT NULL, min_guests VARCHAR(20) DEFAULT NULL, max_guests VARCHAR(20) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, instagram VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_80161466989D9B62 ON caterer_profile (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_801614667E3C61F9 ON caterer_profile (owner_id)');
        $this->addSql('CREATE TABLE menu_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, price_per_person NUMERIC(8, 2) DEFAULT NULL, category VARCHAR(50) NOT NULL, is_vegetarian BOOLEAN NOT NULL, is_vegan BOOLEAN NOT NULL, is_gluten_free BOOLEAN NOT NULL, image_url VARCHAR(500) DEFAULT NULL, caterer_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D754D550F0611026 ON menu_item (caterer_profile_id)');
        $this->addSql('CREATE TABLE quote_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_type VARCHAR(50) NOT NULL, event_date DATE NOT NULL, guest_count INT NOT NULL, budget NUMERIC(10, 2) DEFAULT NULL, message TEXT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_id INT NOT NULL, caterer_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D478271B19EB6921 ON quote_request (client_id)');
        $this->addSql('CREATE INDEX IDX_D478271BF0611026 ON quote_request (caterer_profile_id)');
        $this->addSql('ALTER TABLE caterer_profile ADD CONSTRAINT FK_801614667E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D550F0611026 FOREIGN KEY (caterer_profile_id) REFERENCES caterer_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quote_request ADD CONSTRAINT FK_D478271B19EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quote_request ADD CONSTRAINT FK_D478271BF0611026 FOREIGN KEY (caterer_profile_id) REFERENCES caterer_profile (id) NOT DEFERRABLE');
        $this->addSql('DROP TABLE book');
        $this->addSql('DROP TABLE greeting');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT fk_794381c616a2b381');
        $this->addSql('DROP INDEX idx_794381c616a2b381');
        $this->addSql('ALTER TABLE review ADD title VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE review ADD caterer_profile_id INT NOT NULL');
        $this->addSql('ALTER TABLE review ADD author_id INT NOT NULL');
        $this->addSql('ALTER TABLE review DROP author');
        $this->addSql('ALTER TABLE review DROP book_id');
        $this->addSql('ALTER TABLE review RENAME COLUMN publication_date TO created_at');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6F0611026 FOREIGN KEY (caterer_profile_id) REFERENCES caterer_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_794381C6F0611026 ON review (caterer_profile_id)');
        $this->addSql('CREATE INDEX IDX_794381C6F675F31B ON review (author_id)');
        $this->addSql('ALTER TABLE "user" ADD first_name VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD last_name VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD phone VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD user_type VARCHAR(20) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE greeting_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE book (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, isbn VARCHAR(255) DEFAULT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, author VARCHAR(255) NOT NULL, publication_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE greeting (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE caterer_profile DROP CONSTRAINT FK_801614667E3C61F9');
        $this->addSql('ALTER TABLE menu_item DROP CONSTRAINT FK_D754D550F0611026');
        $this->addSql('ALTER TABLE quote_request DROP CONSTRAINT FK_D478271B19EB6921');
        $this->addSql('ALTER TABLE quote_request DROP CONSTRAINT FK_D478271BF0611026');
        $this->addSql('DROP TABLE caterer_profile');
        $this->addSql('DROP TABLE menu_item');
        $this->addSql('DROP TABLE quote_request');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6F0611026');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6F675F31B');
        $this->addSql('DROP INDEX IDX_794381C6F0611026');
        $this->addSql('DROP INDEX IDX_794381C6F675F31B');
        $this->addSql('ALTER TABLE review ADD author VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE review ADD book_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE review DROP title');
        $this->addSql('ALTER TABLE review DROP caterer_profile_id');
        $this->addSql('ALTER TABLE review DROP author_id');
        $this->addSql('ALTER TABLE review RENAME COLUMN created_at TO publication_date');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT fk_794381c616a2b381 FOREIGN KEY (book_id) REFERENCES book (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_794381c616a2b381 ON review (book_id)');
        $this->addSql('ALTER TABLE "user" DROP first_name');
        $this->addSql('ALTER TABLE "user" DROP last_name');
        $this->addSql('ALTER TABLE "user" DROP phone');
        $this->addSql('ALTER TABLE "user" DROP user_type');
    }
}
