<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260420020342 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE greeting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT NOT NULL, photo_url VARCHAR(255) DEFAULT NULL, is_acknowledged BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, wedding_profile_id INT NOT NULL, guest_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_46E3A4ABA3467B4F ON greeting (wedding_profile_id)');
        $this->addSql('CREATE INDEX IDX_46E3A4AB9A4AA658 ON greeting (guest_id)');
        $this->addSql('CREATE TABLE wedding_elders (wedding_profile_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (wedding_profile_id, user_id))');
        $this->addSql('CREATE INDEX IDX_1ADAA87AA3467B4F ON wedding_elders (wedding_profile_id)');
        $this->addSql('CREATE INDEX IDX_1ADAA87AA76ED395 ON wedding_elders (user_id)');
        $this->addSql('ALTER TABLE greeting ADD CONSTRAINT FK_46E3A4ABA3467B4F FOREIGN KEY (wedding_profile_id) REFERENCES wedding_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE greeting ADD CONSTRAINT FK_46E3A4AB9A4AA658 FOREIGN KEY (guest_id) REFERENCES guest (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wedding_elders ADD CONSTRAINT FK_1ADAA87AA3467B4F FOREIGN KEY (wedding_profile_id) REFERENCES wedding_profile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wedding_elders ADD CONSTRAINT FK_1ADAA87AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wedding_profile ADD partner_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE wedding_profile ADD CONSTRAINT FK_EB6634A29393F8FE FOREIGN KEY (partner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_EB6634A29393F8FE ON wedding_profile (partner_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE greeting DROP CONSTRAINT FK_46E3A4ABA3467B4F');
        $this->addSql('ALTER TABLE greeting DROP CONSTRAINT FK_46E3A4AB9A4AA658');
        $this->addSql('ALTER TABLE wedding_elders DROP CONSTRAINT FK_1ADAA87AA3467B4F');
        $this->addSql('ALTER TABLE wedding_elders DROP CONSTRAINT FK_1ADAA87AA76ED395');
        $this->addSql('DROP TABLE greeting');
        $this->addSql('DROP TABLE wedding_elders');
        $this->addSql('ALTER TABLE wedding_profile DROP CONSTRAINT FK_EB6634A29393F8FE');
        $this->addSql('DROP INDEX IDX_EB6634A29393F8FE');
        $this->addSql('ALTER TABLE wedding_profile DROP partner_id');
    }
}
