<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260314082302 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // 1. Drop existing constraints from tables depending on caterer_profile
        $this->addSql('ALTER TABLE menu_item DROP CONSTRAINT fk_d754d550f0611026');
        $this->addSql('ALTER TABLE quote_request DROP CONSTRAINT fk_d478271bf0611026');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT fk_794381c6f0611026');
        $this->addSql('ALTER TABLE caterer_profile DROP CONSTRAINT fk_801614667e3c61f9');

        // 2. Rename the profile table
        $this->addSql('ALTER TABLE caterer_profile RENAME TO vendor_profile');
        $this->addSql('ALTER INDEX uniq_80161466989d9b62 RENAME TO UNIQ_9F209260989D9B62');
        $this->addSql('ALTER INDEX uniq_801614667e3c61f9 RENAME TO UNIQ_9F2092607E3C61F9');

        // 3. Update sequences (if any, serial/identity handles this automatically in PG15)
        
        // 4. Add new columns to vendor_profile
        $this->addSql('ALTER TABLE vendor_profile ADD category VARCHAR(50) NOT NULL DEFAULT \'other\'');
        $this->addSql('ALTER TABLE vendor_profile ADD tags JSON NOT NULL DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE vendor_profile ADD whatsapp VARCHAR(50) NOT NULL DEFAULT \'\'');
        $this->addSql('ALTER TABLE vendor_profile ADD languages_spoken JSON NOT NULL DEFAULT \'["ary", "fr"]\'');
        $this->addSql('ALTER TABLE vendor_profile ADD is_featured BOOLEAN NOT NULL DEFAULT FALSE');
        $this->addSql('ALTER TABLE vendor_profile ADD subscription_tier VARCHAR(20) NOT NULL DEFAULT \'free\'');
        
        // 5. Transform existing caterer-specific columns to generic ones if needed
        // (cuisine_types and service_styles are already JSON, we'll keep them but entity uses 'tags')
        $this->addSql('UPDATE vendor_profile SET tags = cuisine_types'); 
        $this->addSql('ALTER TABLE vendor_profile DROP cuisine_types');
        $this->addSql('ALTER TABLE vendor_profile DROP service_styles');

        // 6. Create new tables
        $this->addSql('CREATE TABLE wedding_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, bride_name VARCHAR(255) NOT NULL, groom_name VARCHAR(255) NOT NULL, wedding_date DATE DEFAULT NULL, wedding_city VARCHAR(255) DEFAULT NULL, guest_count_est INT DEFAULT NULL, total_budget_mad INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB6634A2A76ED395 ON wedding_profile (user_id)');
        
        $this->addSql('CREATE TABLE budget_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(100) NOT NULL, budgeted_amount INT NOT NULL, spent_amount INT NOT NULL, display_order INT NOT NULL, wedding_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65DF274EA3467B4F ON budget_item (wedding_profile_id)');
        
        $this->addSql('CREATE TABLE checklist_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(100) NOT NULL, months_before INT DEFAULT NULL, due_date DATE DEFAULT NULL, assigned_to VARCHAR(100) DEFAULT NULL, status VARCHAR(20) NOT NULL, notes TEXT DEFAULT NULL, is_default BOOLEAN NOT NULL, display_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, wedding_profile_id INT NOT NULL, vendor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D48EDEC2A3467B4F ON checklist_task (wedding_profile_id)');
        $this->addSql('CREATE INDEX IDX_D48EDEC2F603EE73 ON checklist_task (vendor_id)');
        
        $this->addSql('CREATE TABLE guest (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, full_name VARCHAR(255) NOT NULL, phone VARCHAR(30) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, side VARCHAR(10) NOT NULL, relationship VARCHAR(100) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, rsvp_status VARCHAR(15) NOT NULL, meal_preference VARCHAR(20) DEFAULT NULL, table_number INT DEFAULT NULL, invitation_sent BOOLEAN NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, wedding_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ACB79A35A3467B4F ON guest (wedding_profile_id)');

        // 7. Rename foreign key columns and add new constraints
        $this->addSql('ALTER TABLE menu_item RENAME COLUMN caterer_profile_id TO vendor_profile_id');
        $this->addSql('DROP INDEX idx_d754d550f0611026');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D550568FC6DF FOREIGN KEY (vendor_profile_id) REFERENCES vendor_profile (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_D754D550568FC6DF ON menu_item (vendor_profile_id)');

        $this->addSql('ALTER TABLE quote_request RENAME COLUMN caterer_profile_id TO vendor_profile_id');
        $this->addSql('DROP INDEX idx_d478271bf0611026');
        $this->addSql('ALTER TABLE quote_request ADD CONSTRAINT FK_D478271B568FC6DF FOREIGN KEY (vendor_profile_id) REFERENCES vendor_profile (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_D478271B568FC6DF ON quote_request (vendor_profile_id)');

        $this->addSql('ALTER TABLE review RENAME COLUMN caterer_profile_id TO vendor_profile_id');
        $this->addSql('DROP INDEX idx_794381c6f0611026');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6568FC6DF FOREIGN KEY (vendor_profile_id) REFERENCES vendor_profile (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_794381C6568FC6DF ON review (vendor_profile_id)');

        $this->addSql('ALTER TABLE vendor_profile ADD CONSTRAINT FK_9F2092607E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wedding_profile ADD CONSTRAINT FK_EB6634A2A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE budget_item ADD CONSTRAINT FK_65DF274EA3467B4F FOREIGN KEY (wedding_profile_id) REFERENCES wedding_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE checklist_task ADD CONSTRAINT FK_D48EDEC2A3467B4F FOREIGN KEY (wedding_profile_id) REFERENCES wedding_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE checklist_task ADD CONSTRAINT FK_D48EDEC2F603EE73 FOREIGN KEY (vendor_id) REFERENCES vendor_profile (id)');
        $this->addSql('ALTER TABLE guest ADD CONSTRAINT FK_ACB79A35A3467B4F FOREIGN KEY (wedding_profile_id) REFERENCES wedding_profile (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE caterer_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, business_name VARCHAR(255) NOT NULL, tagline VARCHAR(255) DEFAULT NULL, description TEXT NOT NULL, cuisine_types JSON NOT NULL, service_styles JSON NOT NULL, service_area VARCHAR(255) NOT NULL, price_range VARCHAR(10) NOT NULL, cover_image_url VARCHAR(500) DEFAULT NULL, gallery_images JSON NOT NULL, average_rating NUMERIC(3, 2) DEFAULT NULL, review_count INT NOT NULL, is_verified BOOLEAN NOT NULL, min_guests VARCHAR(20) DEFAULT NULL, max_guests VARCHAR(20) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, instagram VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_80161466989d9b62 ON caterer_profile (slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_801614667e3c61f9 ON caterer_profile (owner_id)');
        $this->addSql('ALTER TABLE caterer_profile ADD CONSTRAINT fk_801614667e3c61f9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE budget_item DROP CONSTRAINT FK_65DF274EA3467B4F');
        $this->addSql('ALTER TABLE checklist_task DROP CONSTRAINT FK_D48EDEC2A3467B4F');
        $this->addSql('ALTER TABLE checklist_task DROP CONSTRAINT FK_D48EDEC2F603EE73');
        $this->addSql('ALTER TABLE guest DROP CONSTRAINT FK_ACB79A35A3467B4F');
        $this->addSql('ALTER TABLE vendor_profile DROP CONSTRAINT FK_9F2092607E3C61F9');
        $this->addSql('ALTER TABLE wedding_profile DROP CONSTRAINT FK_EB6634A2A76ED395');
        $this->addSql('DROP TABLE budget_item');
        $this->addSql('DROP TABLE checklist_task');
        $this->addSql('DROP TABLE guest');
        $this->addSql('DROP TABLE vendor_profile');
        $this->addSql('DROP TABLE wedding_profile');
        $this->addSql('ALTER TABLE menu_item DROP CONSTRAINT FK_D754D550568FC6DF');
        $this->addSql('DROP INDEX IDX_D754D550568FC6DF');
        $this->addSql('ALTER TABLE menu_item RENAME COLUMN vendor_profile_id TO caterer_profile_id');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT fk_d754d550f0611026 FOREIGN KEY (caterer_profile_id) REFERENCES caterer_profile (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_d754d550f0611026 ON menu_item (caterer_profile_id)');
        $this->addSql('ALTER TABLE quote_request DROP CONSTRAINT FK_D478271B568FC6DF');
        $this->addSql('DROP INDEX IDX_D478271B568FC6DF');
        $this->addSql('ALTER TABLE quote_request RENAME COLUMN vendor_profile_id TO caterer_profile_id');
        $this->addSql('ALTER TABLE quote_request ADD CONSTRAINT fk_d478271bf0611026 FOREIGN KEY (caterer_profile_id) REFERENCES caterer_profile (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_d478271bf0611026 ON quote_request (caterer_profile_id)');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6568FC6DF');
        $this->addSql('DROP INDEX IDX_794381C6568FC6DF');
        $this->addSql('ALTER TABLE review RENAME COLUMN vendor_profile_id TO caterer_profile_id');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT fk_794381c6f0611026 FOREIGN KEY (caterer_profile_id) REFERENCES caterer_profile (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_794381c6f0611026 ON review (caterer_profile_id)');
    }
}
