<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260419172425 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE article (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, content TEXT NOT NULL, excerpt TEXT DEFAULT NULL, featured_image VARCHAR(255) DEFAULT NULL, is_published BOOLEAN NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT NOT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23A0E66989D9B62 ON article (slug)');
        $this->addSql('CREATE INDEX IDX_23A0E6612469DE2 ON article (category_id)');
        $this->addSql('CREATE INDEX IDX_23A0E66F675F31B ON article (author_id)');
        $this->addSql('CREATE TABLE article_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_53A4EDAA989D9B62 ON article_category (slug)');
        $this->addSql('CREATE TABLE inspiration_photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image_path VARCHAR(255) NOT NULL, caption VARCHAR(255) DEFAULT NULL, style VARCHAR(100) DEFAULT NULL, is_approved BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT DEFAULT NULL, city_id INT DEFAULT NULL, vendor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1D11826212469DE2 ON inspiration_photo (category_id)');
        $this->addSql('CREATE INDEX IDX_1D1182628BAC62AF ON inspiration_photo (city_id)');
        $this->addSql('CREATE INDEX IDX_1D118262F603EE73 ON inspiration_photo (vendor_id)');
        $this->addSql('CREATE TABLE saved_photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, photo_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_79645F01A76ED395 ON saved_photo (user_id)');
        $this->addSql('CREATE INDEX IDX_79645F017E9E4C8C ON saved_photo (photo_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_photo ON saved_photo (user_id, photo_id)');
        $this->addSql('CREATE TABLE wedding_story (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, couple_names VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, vibe VARCHAR(255) NOT NULL, cover_image VARCHAR(255) NOT NULL, description TEXT NOT NULL, gallery JSON NOT NULL, vendor_credits JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB1FD8EC989D9B62 ON wedding_story (slug)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E6612469DE2 FOREIGN KEY (category_id) REFERENCES article_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inspiration_photo ADD CONSTRAINT FK_1D11826212469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inspiration_photo ADD CONSTRAINT FK_1D1182628BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inspiration_photo ADD CONSTRAINT FK_1D118262F603EE73 FOREIGN KEY (vendor_id) REFERENCES vendor_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE saved_photo ADD CONSTRAINT FK_79645F01A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE saved_photo ADD CONSTRAINT FK_79645F017E9E4C8C FOREIGN KEY (photo_id) REFERENCES inspiration_photo (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE article DROP CONSTRAINT FK_23A0E6612469DE2');
        $this->addSql('ALTER TABLE article DROP CONSTRAINT FK_23A0E66F675F31B');
        $this->addSql('ALTER TABLE inspiration_photo DROP CONSTRAINT FK_1D11826212469DE2');
        $this->addSql('ALTER TABLE inspiration_photo DROP CONSTRAINT FK_1D1182628BAC62AF');
        $this->addSql('ALTER TABLE inspiration_photo DROP CONSTRAINT FK_1D118262F603EE73');
        $this->addSql('ALTER TABLE saved_photo DROP CONSTRAINT FK_79645F01A76ED395');
        $this->addSql('ALTER TABLE saved_photo DROP CONSTRAINT FK_79645F017E9E4C8C');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE article_category');
        $this->addSql('DROP TABLE inspiration_photo');
        $this->addSql('DROP TABLE saved_photo');
        $this->addSql('DROP TABLE wedding_story');
    }
}
