<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260723025956 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE saved_vendor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, vendor_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_912448EDA76ED395 ON saved_vendor (user_id)');
        $this->addSql('CREATE INDEX IDX_912448ED568FC6DF ON saved_vendor (vendor_profile_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_vendor ON saved_vendor (user_id, vendor_profile_id)');
        $this->addSql('ALTER TABLE saved_vendor ADD CONSTRAINT FK_912448EDA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE saved_vendor ADD CONSTRAINT FK_912448ED568FC6DF FOREIGN KEY (vendor_profile_id) REFERENCES vendor_profile (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE saved_vendor DROP CONSTRAINT FK_912448EDA76ED395');
        $this->addSql('ALTER TABLE saved_vendor DROP CONSTRAINT FK_912448ED568FC6DF');
        $this->addSql('DROP TABLE saved_vendor');
    }
}
