<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260314043941 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE caterer_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, business_name VARCHAR(255) NOT NULL, tagline VARCHAR(255) DEFAULT NULL, description TEXT NOT NULL, cuisine_types JSON NOT NULL, service_styles JSON NOT NULL, service_area VARCHAR(255) NOT NULL, price_range VARCHAR(10) NOT NULL, cover_image_url VARCHAR(500) DEFAULT NULL, gallery_images JSON NOT NULL, average_rating NUMERIC(3, 2) DEFAULT NULL, review_count INT NOT NULL, is_verified BOOLEAN NOT NULL, min_guests VARCHAR(20) DEFAULT NULL, max_guests VARCHAR(20) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, instagram VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_80161466989D9B62 ON caterer_profile (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_801614667E3C61F9 ON caterer_profile (owner_id)');
        $this->addSql('CREATE TABLE menu_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, price_per_person NUMERIC(8, 2) DEFAULT NULL, category VARCHAR(50) NOT NULL, is_vegetarian BOOLEAN NOT NULL, is_vegan BOOLEAN NOT NULL, is_gluten_free BOOLEAN NOT NULL, image_url VARCHAR(500) DEFAULT NULL, caterer_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D754D550F0611026 ON menu_item (caterer_profile_id)');
        $this->addSql('CREATE TABLE quote_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_type VARCHAR(50) NOT NULL, event_date DATE NOT NULL, guest_count INT NOT NULL, budget NUMERIC(10, 2) DEFAULT NULL, message TEXT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_id INT NOT NULL, caterer_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D478271B19EB6921 ON quote_request (client_id)');
        $this->addSql('CREATE INDEX IDX_D478271BF0611026 ON quote_request (caterer_profile_id)');
        $this->addSql('CREATE TABLE review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rating SMALLINT NOT NULL, title VARCHAR(255) DEFAULT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, caterer_profile_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_794381C6F0611026 ON review (caterer_profile_id)');
        $this->addSql('CREATE INDEX IDX_794381C6F675F31B ON review (author_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(30) DEFAULT NULL, user_type VARCHAR(20) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE caterer_profile ADD CONSTRAINT FK_801614667E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D550F0611026 FOREIGN KEY (caterer_profile_id) REFERENCES caterer_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quote_request ADD CONSTRAINT FK_D478271B19EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quote_request ADD CONSTRAINT FK_D478271BF0611026 FOREIGN KEY (caterer_profile_id) REFERENCES caterer_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6F0611026 FOREIGN KEY (caterer_profile_id) REFERENCES caterer_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE caterer_profile DROP CONSTRAINT FK_801614667E3C61F9');
        $this->addSql('ALTER TABLE menu_item DROP CONSTRAINT FK_D754D550F0611026');
        $this->addSql('ALTER TABLE quote_request DROP CONSTRAINT FK_D478271B19EB6921');
        $this->addSql('ALTER TABLE quote_request DROP CONSTRAINT FK_D478271BF0611026');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6F0611026');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6F675F31B');
        $this->addSql('DROP TABLE caterer_profile');
        $this->addSql('DROP TABLE menu_item');
        $this->addSql('DROP TABLE quote_request');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE "user"');
    }
}
