<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260314140736 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ext_translations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(8) NOT NULL, object_class VARCHAR(191) NOT NULL, field VARCHAR(32) NOT NULL, foreign_key VARCHAR(64) NOT NULL, content TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX translations_lookup_idx ON ext_translations (locale, object_class, foreign_key)');
        $this->addSql('CREATE INDEX translations_field_idx ON ext_translations (field, object_class, foreign_key)');
        $this->addSql('ALTER TABLE vendor_profile ALTER category DROP DEFAULT');
        $this->addSql('ALTER TABLE vendor_profile ALTER tags DROP DEFAULT');
        $this->addSql('ALTER TABLE vendor_profile ALTER whatsapp DROP DEFAULT');
        $this->addSql('ALTER TABLE vendor_profile ALTER languages_spoken DROP DEFAULT');
        $this->addSql('ALTER TABLE vendor_profile ALTER is_featured DROP DEFAULT');
        $this->addSql('ALTER TABLE vendor_profile ALTER subscription_tier DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE ext_translations');
        $this->addSql('ALTER TABLE vendor_profile ALTER category SET DEFAULT \'other\'');
        $this->addSql('ALTER TABLE vendor_profile ALTER tags SET DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE vendor_profile ALTER whatsapp SET DEFAULT \'\'');
        $this->addSql('ALTER TABLE vendor_profile ALTER languages_spoken SET DEFAULT \'["ary", "fr"]\'');
        $this->addSql('ALTER TABLE vendor_profile ALTER is_featured SET DEFAULT false');
        $this->addSql('ALTER TABLE vendor_profile ALTER subscription_tier SET DEFAULT \'free\'');
    }
}
