<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315145904 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C1989D9B62 ON category (slug)');
        $this->addSql('CREATE TABLE city (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D5B0234989D9B62 ON city (slug)');
        $this->addSql('CREATE TABLE vendor_profile_city (vendor_profile_id INT NOT NULL, city_id INT NOT NULL, PRIMARY KEY (vendor_profile_id, city_id))');
        $this->addSql('CREATE INDEX IDX_3091FC78568FC6DF ON vendor_profile_city (vendor_profile_id)');
        $this->addSql('CREATE INDEX IDX_3091FC788BAC62AF ON vendor_profile_city (city_id)');
        $this->addSql('ALTER TABLE vendor_profile_city ADD CONSTRAINT FK_3091FC78568FC6DF FOREIGN KEY (vendor_profile_id) REFERENCES vendor_profile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vendor_profile_city ADD CONSTRAINT FK_3091FC788BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vendor_profile ADD category_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE vendor_profile DROP category');
        $this->addSql('ALTER TABLE vendor_profile ADD CONSTRAINT FK_9F20926012469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_9F20926012469DE2 ON vendor_profile (category_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE vendor_profile_city DROP CONSTRAINT FK_3091FC78568FC6DF');
        $this->addSql('ALTER TABLE vendor_profile_city DROP CONSTRAINT FK_3091FC788BAC62AF');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE vendor_profile_city');
        $this->addSql('ALTER TABLE vendor_profile DROP CONSTRAINT FK_9F20926012469DE2');
        $this->addSql('DROP INDEX IDX_9F20926012469DE2');
        $this->addSql('ALTER TABLE vendor_profile ADD category VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE vendor_profile DROP category_id');
    }
}
