<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260417190831 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE timeline_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, time VARCHAR(10) NOT NULL, title VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, icon VARCHAR(50) DEFAULT NULL, display_order INT NOT NULL, wedding_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1E13D06BA3467B4F ON timeline_item (wedding_profile_id)');
        $this->addSql('ALTER TABLE timeline_item ADD CONSTRAINT FK_1E13D06BA3467B4F FOREIGN KEY (wedding_profile_id) REFERENCES wedding_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wedding_profile ADD registry_url VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE wedding_profile ADD accommodation_info TEXT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE timeline_item DROP CONSTRAINT FK_1E13D06BA3467B4F');
        $this->addSql('DROP TABLE timeline_item');
        $this->addSql('ALTER TABLE wedding_profile DROP registry_url');
        $this->addSql('ALTER TABLE wedding_profile DROP accommodation_info');
    }
}
