<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260722231706 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE article (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, content TEXT NOT NULL, excerpt TEXT DEFAULT NULL, featured_image VARCHAR(255) DEFAULT NULL, is_published BOOLEAN NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_featured BOOLEAN NOT NULL, featured_order INT DEFAULT NULL, tags JSON NOT NULL, widget_type VARCHAR(32) DEFAULT NULL, category_id INT NOT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23A0E66989D9B62 ON article (slug)');
        $this->addSql('CREATE INDEX IDX_23A0E6612469DE2 ON article (category_id)');
        $this->addSql('CREATE INDEX IDX_23A0E66F675F31B ON article (author_id)');
        $this->addSql('CREATE TABLE article_vendor_profile (article_id INT NOT NULL, vendor_profile_id INT NOT NULL, PRIMARY KEY (article_id, vendor_profile_id))');
        $this->addSql('CREATE INDEX IDX_391B1EE87294869C ON article_vendor_profile (article_id)');
        $this->addSql('CREATE INDEX IDX_391B1EE8568FC6DF ON article_vendor_profile (vendor_profile_id)');
        $this->addSql('CREATE TABLE article_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, icon_svg TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_53A4EDAA989D9B62 ON article_category (slug)');
        $this->addSql('CREATE TABLE budget_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(100) NOT NULL, budgeted_amount INT NOT NULL, spent_amount INT NOT NULL, display_order INT NOT NULL, wedding_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65DF274EA3467B4F ON budget_item (wedding_profile_id)');
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, emoji VARCHAR(10) DEFAULT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C1989D9B62 ON category (slug)');
        $this->addSql('CREATE TABLE checklist_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(100) NOT NULL, months_before INT DEFAULT NULL, due_date DATE DEFAULT NULL, assigned_to VARCHAR(100) DEFAULT NULL, status VARCHAR(20) NOT NULL, notes TEXT DEFAULT NULL, is_default BOOLEAN NOT NULL, display_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, wedding_profile_id INT NOT NULL, vendor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D48EDEC2A3467B4F ON checklist_task (wedding_profile_id)');
        $this->addSql('CREATE INDEX IDX_D48EDEC2F603EE73 ON checklist_task (vendor_id)');
        $this->addSql('CREATE TABLE city (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D5B0234989D9B62 ON city (slug)');
        $this->addSql('CREATE TABLE ext_translations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(8) NOT NULL, object_class VARCHAR(191) NOT NULL, field VARCHAR(32) NOT NULL, foreign_key VARCHAR(64) NOT NULL, content TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX translations_lookup_idx ON ext_translations (locale, object_class, foreign_key)');
        $this->addSql('CREATE INDEX translations_field_idx ON ext_translations (field, object_class, foreign_key)');
        $this->addSql('CREATE TABLE greeting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT NOT NULL, photo_url VARCHAR(255) DEFAULT NULL, is_acknowledged BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, wedding_profile_id INT NOT NULL, guest_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_46E3A4ABA3467B4F ON greeting (wedding_profile_id)');
        $this->addSql('CREATE INDEX IDX_46E3A4AB9A4AA658 ON greeting (guest_id)');
        $this->addSql('CREATE TABLE guest (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guest_token VARCHAR(64) NOT NULL, full_name VARCHAR(255) NOT NULL, phone VARCHAR(30) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, side VARCHAR(10) NOT NULL, relationship VARCHAR(100) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, rsvp_status VARCHAR(15) NOT NULL, meal_preference VARCHAR(20) DEFAULT NULL, table_number INT DEFAULT NULL, invitation_sent BOOLEAN NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, wedding_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ACB79A354AC9362F ON guest (guest_token)');
        $this->addSql('CREATE INDEX IDX_ACB79A35A3467B4F ON guest (wedding_profile_id)');
        $this->addSql('CREATE TABLE inspiration_photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image_path VARCHAR(255) NOT NULL, caption VARCHAR(255) DEFAULT NULL, style VARCHAR(100) DEFAULT NULL, is_approved BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT DEFAULT NULL, city_id INT DEFAULT NULL, vendor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1D11826212469DE2 ON inspiration_photo (category_id)');
        $this->addSql('CREATE INDEX IDX_1D1182628BAC62AF ON inspiration_photo (city_id)');
        $this->addSql('CREATE INDEX IDX_1D118262F603EE73 ON inspiration_photo (vendor_id)');
        $this->addSql('CREATE TABLE menu_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, price_per_person NUMERIC(8, 2) DEFAULT NULL, category VARCHAR(50) NOT NULL, is_vegetarian BOOLEAN NOT NULL, is_vegan BOOLEAN NOT NULL, is_gluten_free BOOLEAN NOT NULL, image_url VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, vendor_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D754D550568FC6DF ON menu_item (vendor_profile_id)');
        $this->addSql('CREATE TABLE permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E04992AA5E237E06 ON permission (name)');
        $this->addSql('CREATE TABLE quote_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_type VARCHAR(50) NOT NULL, event_date DATE NOT NULL, guest_count INT NOT NULL, budget NUMERIC(10, 2) DEFAULT NULL, message TEXT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, client_id INT NOT NULL, vendor_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_quote_vendor_profile ON quote_request (vendor_profile_id)');
        $this->addSql('CREATE INDEX idx_quote_client ON quote_request (client_id)');
        $this->addSql('CREATE INDEX idx_quote_status ON quote_request (status)');
        $this->addSql('CREATE INDEX idx_quote_created ON quote_request (created_at)');
        $this->addSql('CREATE TABLE refresh_token (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C74F2195C74F2195 ON refresh_token (refresh_token)');
        $this->addSql('CREATE TABLE review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rating SMALLINT NOT NULL, title VARCHAR(255) DEFAULT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, vendor_profile_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_review_vendor_profile ON review (vendor_profile_id)');
        $this->addSql('CREATE INDEX idx_review_author ON review (author_id)');
        $this->addSql('CREATE INDEX idx_review_created ON review (created_at)');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_57698A6A5E237E06 ON role (name)');
        $this->addSql('CREATE TABLE role_permission (role_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY (role_id, permission_id))');
        $this->addSql('CREATE INDEX IDX_6F7DF886D60322AC ON role_permission (role_id)');
        $this->addSql('CREATE INDEX IDX_6F7DF886FED90CCA ON role_permission (permission_id)');
        $this->addSql('CREATE TABLE saved_photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, photo_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_79645F01A76ED395 ON saved_photo (user_id)');
        $this->addSql('CREATE INDEX IDX_79645F017E9E4C8C ON saved_photo (photo_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_photo ON saved_photo (user_id, photo_id)');
        $this->addSql('CREATE TABLE timeline_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, time VARCHAR(10) NOT NULL, title VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, icon VARCHAR(50) DEFAULT NULL, display_order INT NOT NULL, wedding_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1E13D06BA3467B4F ON timeline_item (wedding_profile_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(20) DEFAULT NULL, user_type VARCHAR(20) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, google_id VARCHAR(255) DEFAULT NULL, password_reset_token VARCHAR(100) DEFAULT NULL, password_reset_token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_verified BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D64976F5C865 ON "user" (google_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_roles (user_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (user_id, role_id))');
        $this->addSql('CREATE INDEX IDX_54FCD59FA76ED395 ON user_roles (user_id)');
        $this->addSql('CREATE INDEX IDX_54FCD59FD60322AC ON user_roles (role_id)');
        $this->addSql('CREATE TABLE vendor_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, business_name VARCHAR(255) NOT NULL, tagline VARCHAR(255) DEFAULT NULL, description TEXT NOT NULL, tags JSON NOT NULL, price_range VARCHAR(10) NOT NULL, starting_price INT DEFAULT NULL, cover_image_url VARCHAR(500) DEFAULT NULL, whatsapp VARCHAR(20) NOT NULL, gallery_images JSON NOT NULL, languages_spoken JSON NOT NULL, average_rating NUMERIC(3, 2) DEFAULT NULL, review_count INT NOT NULL, is_verified BOOLEAN NOT NULL, is_featured BOOLEAN NOT NULL, subscription_tier VARCHAR(20) NOT NULL, min_guests SMALLINT DEFAULT NULL, max_guests SMALLINT DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, instagram VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F209260989D9B62 ON vendor_profile (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F2092607E3C61F9 ON vendor_profile (owner_id)');
        $this->addSql('CREATE INDEX idx_vendor_profile_category ON vendor_profile (category_id)');
        $this->addSql('CREATE INDEX idx_vendor_profile_owner ON vendor_profile (owner_id)');
        $this->addSql('CREATE INDEX idx_vendor_profile_avg_rating ON vendor_profile (average_rating)');
        $this->addSql('CREATE INDEX idx_vendor_profile_review_count ON vendor_profile (review_count)');
        $this->addSql('CREATE INDEX idx_vendor_profile_created ON vendor_profile (created_at)');
        $this->addSql('CREATE INDEX idx_vendor_profile_verified ON vendor_profile (is_verified)');
        $this->addSql('CREATE TABLE vendor_profile_city (vendor_profile_id INT NOT NULL, city_id INT NOT NULL, PRIMARY KEY (vendor_profile_id, city_id))');
        $this->addSql('CREATE INDEX IDX_3091FC78568FC6DF ON vendor_profile_city (vendor_profile_id)');
        $this->addSql('CREATE INDEX IDX_3091FC788BAC62AF ON vendor_profile_city (city_id)');
        $this->addSql('CREATE TABLE wedding_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, bride_name VARCHAR(255) NOT NULL, groom_name VARCHAR(255) NOT NULL, wedding_date DATE DEFAULT NULL, wedding_city VARCHAR(255) DEFAULT NULL, venue_name VARCHAR(255) DEFAULT NULL, venue_address VARCHAR(500) DEFAULT NULL, cover_image VARCHAR(255) DEFAULT NULL, guest_count_est INT DEFAULT NULL, total_budget_mad INT DEFAULT NULL, registry_url VARCHAR(500) DEFAULT NULL, accommodation_info TEXT DEFAULT NULL, our_story TEXT DEFAULT NULL, qa JSON DEFAULT NULL, travel_info TEXT DEFAULT NULL, selected_theme VARCHAR(50) DEFAULT \'modern\' NOT NULL, theme_color VARCHAR(20) DEFAULT NULL, gallery_images JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, style_persona VARCHAR(50) DEFAULT NULL, quiz_results JSON DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, partner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB6634A2989D9B62 ON wedding_profile (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB6634A2A76ED395 ON wedding_profile (user_id)');
        $this->addSql('CREATE INDEX IDX_EB6634A29393F8FE ON wedding_profile (partner_id)');
        $this->addSql('CREATE INDEX idx_wedding_profile_user ON wedding_profile (user_id)');
        $this->addSql('CREATE INDEX idx_wedding_profile_slug ON wedding_profile (slug)');
        $this->addSql('CREATE TABLE wedding_elders (wedding_profile_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (wedding_profile_id, user_id))');
        $this->addSql('CREATE INDEX IDX_1ADAA87AA3467B4F ON wedding_elders (wedding_profile_id)');
        $this->addSql('CREATE INDEX IDX_1ADAA87AA76ED395 ON wedding_elders (user_id)');
        $this->addSql('CREATE TABLE wedding_story (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, couple_names VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, vibe VARCHAR(255) NOT NULL, cover_image VARCHAR(255) NOT NULL, description TEXT NOT NULL, gallery JSON NOT NULL, vendor_credits JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_featured BOOLEAN NOT NULL, style VARCHAR(100) DEFAULT NULL, season VARCHAR(50) DEFAULT NULL, color_palette JSON NOT NULL, celebration_timeline JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB1FD8EC989D9B62 ON wedding_story (slug)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E6612469DE2 FOREIGN KEY (category_id) REFERENCES article_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE article_vendor_profile ADD CONSTRAINT FK_391B1EE87294869C FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_vendor_profile ADD CONSTRAINT FK_391B1EE8568FC6DF FOREIGN KEY (vendor_profile_id) REFERENCES vendor_profile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE budget_item ADD CONSTRAINT FK_65DF274EA3467B4F FOREIGN KEY (wedding_profile_id) REFERENCES wedding_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE checklist_task ADD CONSTRAINT FK_D48EDEC2A3467B4F FOREIGN KEY (wedding_profile_id) REFERENCES wedding_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE checklist_task ADD CONSTRAINT FK_D48EDEC2F603EE73 FOREIGN KEY (vendor_id) REFERENCES vendor_profile (id)');
        $this->addSql('ALTER TABLE greeting ADD CONSTRAINT FK_46E3A4ABA3467B4F FOREIGN KEY (wedding_profile_id) REFERENCES wedding_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE greeting ADD CONSTRAINT FK_46E3A4AB9A4AA658 FOREIGN KEY (guest_id) REFERENCES guest (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE guest ADD CONSTRAINT FK_ACB79A35A3467B4F FOREIGN KEY (wedding_profile_id) REFERENCES wedding_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inspiration_photo ADD CONSTRAINT FK_1D11826212469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inspiration_photo ADD CONSTRAINT FK_1D1182628BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inspiration_photo ADD CONSTRAINT FK_1D118262F603EE73 FOREIGN KEY (vendor_id) REFERENCES vendor_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D550568FC6DF FOREIGN KEY (vendor_profile_id) REFERENCES vendor_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quote_request ADD CONSTRAINT FK_D478271B19EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quote_request ADD CONSTRAINT FK_D478271B568FC6DF FOREIGN KEY (vendor_profile_id) REFERENCES vendor_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6568FC6DF FOREIGN KEY (vendor_profile_id) REFERENCES vendor_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE role_permission ADD CONSTRAINT FK_6F7DF886D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE role_permission ADD CONSTRAINT FK_6F7DF886FED90CCA FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE saved_photo ADD CONSTRAINT FK_79645F01A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE saved_photo ADD CONSTRAINT FK_79645F017E9E4C8C FOREIGN KEY (photo_id) REFERENCES inspiration_photo (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE timeline_item ADD CONSTRAINT FK_1E13D06BA3467B4F FOREIGN KEY (wedding_profile_id) REFERENCES wedding_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FD60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vendor_profile ADD CONSTRAINT FK_9F20926012469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vendor_profile ADD CONSTRAINT FK_9F2092607E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vendor_profile_city ADD CONSTRAINT FK_3091FC78568FC6DF FOREIGN KEY (vendor_profile_id) REFERENCES vendor_profile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vendor_profile_city ADD CONSTRAINT FK_3091FC788BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wedding_profile ADD CONSTRAINT FK_EB6634A2A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wedding_profile ADD CONSTRAINT FK_EB6634A29393F8FE FOREIGN KEY (partner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wedding_elders ADD CONSTRAINT FK_1ADAA87AA3467B4F FOREIGN KEY (wedding_profile_id) REFERENCES wedding_profile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wedding_elders ADD CONSTRAINT FK_1ADAA87AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE article DROP CONSTRAINT FK_23A0E6612469DE2');
        $this->addSql('ALTER TABLE article DROP CONSTRAINT FK_23A0E66F675F31B');
        $this->addSql('ALTER TABLE article_vendor_profile DROP CONSTRAINT FK_391B1EE87294869C');
        $this->addSql('ALTER TABLE article_vendor_profile DROP CONSTRAINT FK_391B1EE8568FC6DF');
        $this->addSql('ALTER TABLE budget_item DROP CONSTRAINT FK_65DF274EA3467B4F');
        $this->addSql('ALTER TABLE checklist_task DROP CONSTRAINT FK_D48EDEC2A3467B4F');
        $this->addSql('ALTER TABLE checklist_task DROP CONSTRAINT FK_D48EDEC2F603EE73');
        $this->addSql('ALTER TABLE greeting DROP CONSTRAINT FK_46E3A4ABA3467B4F');
        $this->addSql('ALTER TABLE greeting DROP CONSTRAINT FK_46E3A4AB9A4AA658');
        $this->addSql('ALTER TABLE guest DROP CONSTRAINT FK_ACB79A35A3467B4F');
        $this->addSql('ALTER TABLE inspiration_photo DROP CONSTRAINT FK_1D11826212469DE2');
        $this->addSql('ALTER TABLE inspiration_photo DROP CONSTRAINT FK_1D1182628BAC62AF');
        $this->addSql('ALTER TABLE inspiration_photo DROP CONSTRAINT FK_1D118262F603EE73');
        $this->addSql('ALTER TABLE menu_item DROP CONSTRAINT FK_D754D550568FC6DF');
        $this->addSql('ALTER TABLE quote_request DROP CONSTRAINT FK_D478271B19EB6921');
        $this->addSql('ALTER TABLE quote_request DROP CONSTRAINT FK_D478271B568FC6DF');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6568FC6DF');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6F675F31B');
        $this->addSql('ALTER TABLE role_permission DROP CONSTRAINT FK_6F7DF886D60322AC');
        $this->addSql('ALTER TABLE role_permission DROP CONSTRAINT FK_6F7DF886FED90CCA');
        $this->addSql('ALTER TABLE saved_photo DROP CONSTRAINT FK_79645F01A76ED395');
        $this->addSql('ALTER TABLE saved_photo DROP CONSTRAINT FK_79645F017E9E4C8C');
        $this->addSql('ALTER TABLE timeline_item DROP CONSTRAINT FK_1E13D06BA3467B4F');
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FA76ED395');
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FD60322AC');
        $this->addSql('ALTER TABLE vendor_profile DROP CONSTRAINT FK_9F20926012469DE2');
        $this->addSql('ALTER TABLE vendor_profile DROP CONSTRAINT FK_9F2092607E3C61F9');
        $this->addSql('ALTER TABLE vendor_profile_city DROP CONSTRAINT FK_3091FC78568FC6DF');
        $this->addSql('ALTER TABLE vendor_profile_city DROP CONSTRAINT FK_3091FC788BAC62AF');
        $this->addSql('ALTER TABLE wedding_profile DROP CONSTRAINT FK_EB6634A2A76ED395');
        $this->addSql('ALTER TABLE wedding_profile DROP CONSTRAINT FK_EB6634A29393F8FE');
        $this->addSql('ALTER TABLE wedding_elders DROP CONSTRAINT FK_1ADAA87AA3467B4F');
        $this->addSql('ALTER TABLE wedding_elders DROP CONSTRAINT FK_1ADAA87AA76ED395');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE article_vendor_profile');
        $this->addSql('DROP TABLE article_category');
        $this->addSql('DROP TABLE budget_item');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE checklist_task');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE ext_translations');
        $this->addSql('DROP TABLE greeting');
        $this->addSql('DROP TABLE guest');
        $this->addSql('DROP TABLE inspiration_photo');
        $this->addSql('DROP TABLE menu_item');
        $this->addSql('DROP TABLE permission');
        $this->addSql('DROP TABLE quote_request');
        $this->addSql('DROP TABLE refresh_token');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE role_permission');
        $this->addSql('DROP TABLE saved_photo');
        $this->addSql('DROP TABLE timeline_item');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_roles');
        $this->addSql('DROP TABLE vendor_profile');
        $this->addSql('DROP TABLE vendor_profile_city');
        $this->addSql('DROP TABLE wedding_profile');
        $this->addSql('DROP TABLE wedding_elders');
        $this->addSql('DROP TABLE wedding_story');
    }
}
